//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Flawkee")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.3.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.3.0+3ccc17c9d22e2a0845ef10a14350767703d568c0")]
[assembly: System.Reflection.AssemblyProductAttribute("Emby.Ktuvit.Plugin")]
[assembly: System.Reflection.AssemblyTitleAttribute("Emby.Ktuvit.Plugin")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.3.0")]

// Generated by the MSBuild WriteCodeFragment class.

