//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Flawkee")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.2.1")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.2.1+a2e18676f29bc0120f729e644c9cf5d9209dbcac")]
[assembly: System.Reflection.AssemblyProductAttribute("Emby.Ktuvit.Plugin")]
[assembly: System.Reflection.AssemblyTitleAttribute("Emby.Ktuvit.Plugin")]
[assembly: System.Reflection.AssemblyVersionAttribute("1.0.2.1")]

// Generated by the MSBuild WriteCodeFragment class.

